/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSitesSiteIdRouteImport } from './routes/dashboard/sites/$siteId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSitesSiteIdRoute = DashboardSitesSiteIdRouteImport.update({
  id: '/dashboard/sites/$siteId',
  path: '/dashboard/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/dashboard/sites/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/auth/google/callback'
    | '/dashboard/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/dashboard/sites/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  DashboardSitesSiteIdRoute: typeof DashboardSitesSiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sites/$siteId': {
      id: '/dashboard/sites/$siteId'
      path: '/dashboard/sites/$siteId'
      fullPath: '/dashboard/sites/$siteId'
      preLoaderRoute: typeof DashboardSitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  DashboardSitesSiteIdRoute: DashboardSitesSiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
